kubeProxyReplacement: true 
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
hubble:
  enabled: true
  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 31235
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/hostname: kind-worker3
  relay:
    enabled: true
  enableEnvoyConfig: true
ingressController: # enabled ingress feature from Cilium Service Mesh
  enable: true
  loadbalancerMode: dedicated # each ingress will create its own LB